"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

ROOT_URLCONF = 'core.urls'
WSGI_APPLICATION = 'core.wsgi.application'  # WSGI application for deployment
# Replace with your actual secret key
SECRET_KEY = 'sfk8dr=a$y#%fsal3ng1*%_wzd44w)(357-)4rf@lkiiy*2j1^'

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',          # Required for authentication
    'django.contrib.contenttypes',  # Required for contenttypes framework
    'django.contrib.sessions',      # Required for session management
    'django.contrib.messages',      # Required for messaging framework
    'django.contrib.staticfiles',   # Required for static files
    'crispy_forms',
    'crispy_bootstrap5',
    'analytics',
    'users',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Pointing to core templates
        'DIRS': [BASE_DIR / 'templates'],  # Directory for core templates
        # Pointing to analytics templates
        'APP_DIRS': True,  # Allow Django to look for templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'django.template.context_processors.media',  # For media files      
            ],
        },
    },
]

# Security
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production collectstatic
STATICFILES_DIRS = [BASE_DIR / 'static']  # For development static files
# Add at bottom
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Add at the bottom of settings.py
LOGIN_REDIRECT_URL = 'dashboard'  # Redirect to dashboard after login
LOGOUT_REDIRECT_URL = 'login'     # Redirect to login page after logout
LOGIN_REDIRECT_URL = '/accounts/profile/'
# Redirect to profile page after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to home page after logout
